# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_foodrestriction_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('has_early_pass', models.NullBooleanField()),
                ('has_ticket', models.NullBooleanField()),
                ('has_vehicle_pass', models.NullBooleanField()),
                ('paid_dues', models.BooleanField(default=False)),
                ('bicycle_status', models.CharField(blank=True, choices=[('rent', 'Renting'), ('have', 'Have'), ('need', 'Need')], max_length=10, null=True)),
                ('shift_time_preference', models.CharField(blank=True, choices=[('day', 'Day shifts'), ('night', 'Evening shifts'), ('nopref', 'No preference')], max_length=10, null=True)),
                ('shift_day_preference', models.CharField(blank=True, choices=[('sameday', 'All same day'), ('b2b', 'Back to back days'), ('spread', 'Spread out'), ('nopref', 'No preference')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(blank=True, choices=[('campyurt', 'Camp Yurt'), ('newyurt', 'New Yurt'), ('tent', 'Tent'), ('rv', 'RV'), ('container', 'Container'), ('other', 'Other')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='main.AttendanceProfile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_on_playa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='food_restrictions',
            field=models.ManyToManyField(blank=True, to='main.FoodRestriction'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='housing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='main.HousingGroup'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='job_preferences',
            field=models.ManyToManyField(blank=True, to='main.Job'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='transportation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='main.TransportationMethod'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.Skill'),
        ),
    ]
