# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 13:45
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170821_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[256, 256], upload_to='skill_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[512, 512], upload_to='profile_pictures'),
        ),
    ]
