# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_skill_image_20180420_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
