# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180421_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('fb', 'Facebook'), ('twitter', 'Twitter')], max_length=16)),
                ('link', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='main.UserProfile')),
            ],
        ),
    ]
