# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', through='main.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
