# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_by_admin',
            field=models.NullBooleanField(),
        ),
    ]
