# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180527_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinggroup',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('campyurt', 'Camp Yurt'), ('personalyurt', 'Personal Yurt'), ('tent', 'Tent'), ('rv', 'RV'), ('container', 'Container'), ('other', 'Other'), ('van', 'Van'), ('shiftpod', 'Shiftpod')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
