# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def copy_transportation_method(apps, schema_editor):
    MyModel = apps.get_model('main', 'attendanceprofile')
    MyModel.objects.all().update(to_transportation_method=F('transportation_method'))
    MyModel.objects.all().update(from_transportation_method=F('transportation_method'))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_team_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceprofile',
            name='from_transportation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_attendees', to='main.TransportationMethod'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='to_transportation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_attendees', to='main.TransportationMethod'),
        ),
        migrations.RunPython(copy_transportation_method),
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='transportation_method',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified_by_admin',
            field=models.NullBooleanField(verbose_name='Verified'),
        ),
    ]
