# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_copy_transportation_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='transportation_method',
        ),
    ]
