# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_attendanceprofile_housing_type_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceprofile',
            name='housing_type_preference',
            field=models.CharField(blank=True, choices=[('campyurt', 'Camp Yurt'), ('personalyurt', 'Personal Yurt'), ('tent', 'Tent'), ('rv', 'RV'), ('container', 'Container'), ('van', 'Van'), ('shiftpod', 'Shiftpod'), ('other', 'Other')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='housinggroup',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('campyurt', 'Camp Yurt'), ('personalyurt', 'Personal Yurt'), ('tent', 'Tent'), ('rv', 'RV'), ('container', 'Container'), ('van', 'Van'), ('shiftpod', 'Shiftpod'), ('other', 'Other')], max_length=12, null=True),
        ),
    ]
