# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180628_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_early_crew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_late_crew',
            field=models.BooleanField(default=False),
        ),
    ]
