# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180629_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='housing_type_preference',
        ),
    ]
