# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_attendanceprofile_housing_type_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='job_preferences',
        ),
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='shift_day_preference',
        ),
        migrations.RemoveField(
            model_name='attendanceprofile',
            name='shift_time_preference',
        ),
    ]
